### ISSUE TITLE
Create automated system to compile, and run tests at each pull-request with Travis CI

### ISSUE THREAD

**Issue by diogocezar** [neutronjs/neutron#6]
Could be a good ideia apply travis ci on repository, to build automatically on each new release.

**Comment by thrsouza** [comment]
Hi @diogocezar, sounds good to me. Let's do it! 🚀

**Comment by thrsouza** [comment]
Hello, @diogocezar! The travis-ci was applied in the lastest major release (v3.0.0).
Thanks for this good issue! ;)
